### PR TITLE
Create user

### LINKED ISSUE #4: Create user
An Administrator (ADMIN) user should be able to add other users.

User properties are:

- Username (ID)
- Email
- First Name
- Last Name
- URL (Personal Website)
- Avatar (Should be added by the user later on)
- Password (Should be set by the user later on)

The created user should be given one of the following roles:

- ADMIN (Can administer the entire application, i.e. change its settings and operate on it)
- DEVOP (Can create and administer flows but cannot change application settings)
- VIEW_ONLY (Can only view flows)

Sets of user roles can be changed later on.

The user should received a link allowing him to set his password. The link should expire when it's used or within a pre-definable time.

### PR DESCRIPTION
**Pull request by marcolenzo**
Closes #4

### CODE REVIEW

**Comment by powell-christopher** [comment]
Looks good but do we really want to start worrying about API versioning already? ("/api/v1/user") 

I guess it is fine for now but depending on whether we want to publicly expose the API, we may need to have a more detailed discussion.

Url changes vs accept headers, etc.

**Comment by kurtparis** [comment]
Api versioning in the URL is a bad idea dudes

**Comment by marcolenzo** [comment]
Ok let me drop the versioning and we discuss it later on.  My understanding is that the API is not for "public" use.  In any case, I'm not a fun of the media type since the reality is that if you don't move to hypermedia it's much easier to browse an API from the browser itself with a bunch of GETs than staying playing with curl, postman or similar :) Anyway commit coming your way :)

**Comment by marcolenzo** [comment]
For what concerns API versioning discuss on #15

**Pull request merged**
